app/controllers.py
from uuid import uuid4

from decouple import config
from flask import render_template, Blueprint, redirect, url_for

from app.forms import *
from app.models import *


base = Blueprint('base', __name__, url_prefix='/', template_folder='templates')


@base.route('/', methods=['GET', 'POST'])
def home():

    return render_template('home.html')


@base.route('/find-doctor', methods=['GET', 'POST'])
def find_doctor():

    form = FindDoctor()
    insurance_plans = [(i.id, i.name) for i in InsurancePlan.query.all()]
    form.insurance_plan.choices = [(None, 'Select One')] + insurance_plans

    if form.validate_on_submit():
        return redirect(url_for('base.doctor_results', insurance_plan_id=form.insurance_plan.data))

    return render_template('find_doctor.html', form=form)


@base.route('/doctor-results/<insurance_plan_id>', methods=['GET', 'POST'])
def doctor_results(insurance_plan_id):

    doctor_ids = DoctorPlans.query.filter(DoctorPlans.insurance_plan_id == insurance_plan_id).all()
    doctors = Doctor.query.filter(Doctor.id.in_((i.doctor_id) for i in doctor_ids)).all()
    number = len(doctors)

    return render_template('doctor_results.html', doctors=doctors, number=number)


@base.route('/schedule-appointment/<doctor_id>/', methods=['GET', 'POST'])
def schedule_appointment(doctor_id=None):

    form = ScheduleAppointment()

    doctors = [(i.id, i.full_name) for i in Doctor.query.all()]
    form.doctor.choices = [(None, 'Select One'), ('no-doctor', 'I do not have a doctor')] + doctors

    if doctor_id is not None:
        form.doctor.data = doctor_id

    if form.validate_on_submit():

        appointment_id = str(uuid4())
        patient_id = str(uuid4())

        patient = Patient(
            id=patient_id,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data
        )

        appointment = Appointment(
            id=appointment_id,
            doctor_id=form.doctor.data,
            patient_id=patient_id,
            date=form.date_time.data
        )

        db.session.add(patient)
        db.session.add(appointment)
        db.session.commit()

        return redirect(url_for('base.confirmation', appointment_id=appointment_id))

    return render_template('schedule_appointment.html', form=form)


@base.route('/confirmation/<appointment_id>', methods=['GET', 'POST'])
def confirmation(appointment_id):

    appointment = Appointment.query.filter(Appointment.id == appointment_id).first()

    return render_template('appointment_confirmation.html', appointment=appointment)


@base.route('/seed-database/<secret_key>', methods=['GET', 'POST'])
def seed_database(secret_key):

    if secret_key == config('SECRET_KEY'):

        objects = [
            Doctor(id='3f479383-89a6-453d-a4c9-ef0fe31c2cc1', first_name='Jim', last_name='Halpert', title='M.D.'),
            Doctor(id='4541a10c-f612-484b-99d9-4a71402384d6', first_name='Kevin', last_name='Malone', title='M.D.'),
            Doctor(id='a8b13ef2-9845-446a-b3e0-12c800c329d7', first_name='Bob', last_name='Vance', title='D.O.'),
            Doctor(id='75329673-c317-42fa-92e6-c20dc83b4507', first_name='Phyllis', last_name='Vance', title='M.D.'),
            Doctor(id='0a477404-a585-4904-8642-a812a4bb656a', first_name='Creed', last_name='Bratton', title='M.D.'),
            Doctor(id='5b0ff3ff-a84f-4fcf-a6fb-9084c255ca1f', first_name='Andy', last_name='Bernard', title='D.O.'),
            Doctor(id='0affbf2c-f0c0-4006-8d73-0b32e1df88ee', first_name='Pam', last_name='Beesley-Halpert', title='M.B.B.S.'),
            Doctor(id='bdd8ac9a-114f-4812-bac7-82d425f9209a', first_name='Holly', last_name='Flax-Scott', title='M.D.'),
            Doctor(id='8b1f5048-2000-490c-8d00-6c2a47d9445b', first_name='Michael', last_name='Scott', title='M.D.'),
            Doctor(id='652a059d-e21a-477c-87c0-4d246f4711ce', first_name='Oscar', last_name='Martinez', title='M.D.'),
            Doctor(id='eb5c85ab-92d2-4fbb-aea6-c2239a6314d7', first_name='Toby', last_name='Flenderman', title='D.O.'),
            Doctor(id='3819a75b-993c-4fd1-ac8d-462d3f1517c3', first_name='Erin', last_name='Hannon', title='M.D.'),
            Doctor(id='956df4fe-d135-416c-aa23-6ada74ea47a4', first_name='Ryan', last_name='Howard', title='M.D.'),
            Doctor(id='89080cf0-f73b-4688-9bf2-53f6a7701a3f', first_name='Stanley', last_name='Hudson', title='M.B.B.S.'),
            Doctor(id='28a80f98-7522-4d99-ad21-9fd01c22c13f', first_name='Dwight', last_name='Schrute', title='M.D.'),
            Doctor(id='eb9775ae-ca7a-4af7-9215-ccefffa7cb5c', first_name='David', last_name='Wallace', title='M.D.'),
            Doctor(id='8f773ef4-3ec3-4be2-8a1e-482b82b80d37', first_name='Angela', last_name='Martin-Schrute', title='M.D.'),
            Doctor(id='38175e97-f460-49e1-8675-399aee7b87f1', first_name='Meredith', last_name='Palmer', title='D.O.'),
            Doctor(id='7c76e16d-28ad-4b6f-8e6b-4b373ada6096', first_name='Robert', last_name='California', title='M.D.'),
            Doctor(id='27306b59-c26e-48c9-bdc8-6d86da832a72', first_name='Jo', last_name='Bennett', title='M.B.B.S.'),
            Doctor(id='08e9cd4e-8581-4487-8c25-7408663cd3b4', first_name='Gabe', last_name='Lewis', title='M.D.'),
            Doctor(id='df0607ab-707c-44ce-b3f0-9d1b8f6a38b6', first_name='Karen', last_name='Filippelli', title='D.O.'),
            Doctor(id='4ac5429c-e6a8-4a29-b234-ee2376a725b3', first_name='Jan', last_name='Levinson-Gould', title='M.D.'),
            Doctor(id='28f667ad-b92a-4363-a568-699905e5eccc', first_name='Urkel', last_name='Grue', title='M.B.B.S.'),
            Doctor(id='2d0335ee-a23d-429d-ad4d-d74170a4bcc4', first_name='Darryl', last_name='Philbin', title='M.D.'),
            Doctor(id='b7f9dcda-96a1-4ca0-8f74-69b316f289ff', first_name='Kelly', last_name='Kapoor', title='D.O.'),
            InsuranceCompany(id='a8637ea9-c44b-4073-bac0-81d4f8973b6b', name='Aetna'),
            InsuranceCompany(id='6dfb295b-5ca9-4bd3-ac72-79eaeb1f7419', name='Blue Cross/Blue Shield'),
            InsuranceCompany(id='0c58d4ad-2f51-46f1-9c24-24d649cd938c', name='Cigna'),
            InsuranceCompany(id='4a2ceed4-d274-44d1-87a2-f878c1b2ead0', name='Humana'),
            InsuranceCompany(id='381f0ab3-1fb8-440f-81e6-6902dc60115a', name='HealthPartners'),
            InsuranceCompany(id='0a6f07e1-98c3-4dd8-b362-c718ce36f565', name='FloridaBlue'),
            InsuranceCompany(id='bcc39f7b-7ce0-4aa7-92e1-f8faba4f4ccb', name='UnitedHealth'),
            InsuranceCompany(id='7d4492ba-9903-4d0b-9c0b-d39ad4bb4f5b', name='WellCare'),
            InsuranceCompany(id='8ed93639-2644-4559-a086-09e3bb2da9bd', name='Caresource'),
            InsuranceCompany(id='9c791ef1-d499-434e-9213-edf5ad29ccf2', name='Metropolitan'),
            InsuranceCompany(id='0dd55d91-cd65-45cb-9263-98927e23338e', name='Kaiser Foundation'),
            InsuranceCompany(id='3fe1b051-da8f-40a6-917b-edf9b82d460b', name='Anthem Inc'),
            InsurancePlan(id='6bc112c0-27b6-40a3-8ec9-57921f0868d6', name='Aetna 573', type='HMO', insurance_company_id='a8637ea9-c44b-4073-bac0-81d4f8973b6b'),
            InsurancePlan(id='c2c4166d-95c5-4bcf-9e83-f1388420bfb7', name='Aetna 574', type='HMO', insurance_company_id='a8637ea9-c44b-4073-bac0-81d4f8973b6b'),
            InsurancePlan(id='6e2c4a69-2ba1-4e3e-8fbf-01c1a8b9e2f8', name='Aetna 681', type='HSA', insurance_company_id='a8637ea9-c44b-4073-bac0-81d4f8973b6b'),
            InsurancePlan(id='cfebeba3-47e5-4461-b2ed-9208189e30f0', name='Aetna 888', type='PPO', insurance_company_id='a8637ea9-c44b-4073-bac0-81d4f8973b6b'),
            InsurancePlan(id='5ba6d769-b09d-46e7-b9f2-c92de7a37b0f', name='Blue Cross/Blue Shield 121', type='HMO', insurance_company_id='6dfb295b-5ca9-4bd3-ac72-79eaeb1f7419'),
            InsurancePlan(id='93944eaa-b5e5-458a-a52f-c8c518c6d16f', name='Blue Cross/Blue Shield 122', type='HDHP', insurance_company_id='6dfb295b-5ca9-4bd3-ac72-79eaeb1f7419'),
            InsurancePlan(id='025ee9cc-332c-4ff2-8def-9c47847c3b73', name='Blue Cross/Blue Shield 301', type='HSA', insurance_company_id='6dfb295b-5ca9-4bd3-ac72-79eaeb1f7419'),
            InsurancePlan(id='f5722164-c1dc-4c07-b69d-c01f04960ddf', name='Cigna 754', type='PPO', insurance_company_id='0c58d4ad-2f51-46f1-9c24-24d649cd938c'),
            InsurancePlan(id='ffeb87b4-5781-4f4a-8cab-25612e2912de', name='Cigna 811', type='HSA', insurance_company_id='0c58d4ad-2f51-46f1-9c24-24d649cd938c'),
            InsurancePlan(id='59a06f0a-a0cf-45f2-8597-77e364939958', name='Humana 544', type='HSA', insurance_company_id='4a2ceed4-d274-44d1-87a2-f878c1b2ead0'),
            InsurancePlan(id='db272f54-f85d-4e43-bdbb-273cadb91e5d', name='Humana 311', type='HMO', insurance_company_id='4a2ceed4-d274-44d1-87a2-f878c1b2ead0'),
            InsurancePlan(id='3b6ea032-1e4a-4a87-810d-9c22861c75cd', name='Humana 221', type='PPO', insurance_company_id='4a2ceed4-d274-44d1-87a2-f878c1b2ead0'),
            InsurancePlan(id='75c07b45-fc56-4ef1-b740-764a0627fbe9', name='Humana 712', type='HDHP', insurance_company_id='4a2ceed4-d274-44d1-87a2-f878c1b2ead0'),
            InsurancePlan(id='447bed1f-2f8b-41c1-9dd0-fe8f223ca8ec', name='Humana 312', type='HMO', insurance_company_id='4a2ceed4-d274-44d1-87a2-f878c1b2ead0'),
            InsurancePlan(id='019b1671-8cc9-4119-a79d-fb8ca4dd093e', name='HealthPartners 732', type='HDHP', insurance_company_id='381f0ab3-1fb8-440f-81e6-6902dc60115a'),
            InsurancePlan(id='30f134a7-3947-43d1-b97e-ddceba9b4f66', name='HealthPartners 613', type='HMO', insurance_company_id='381f0ab3-1fb8-440f-81e6-6902dc60115a'),
            InsurancePlan(id='00ee827a-406f-4468-8162-4522badd046c', name='HealthPartners 432', type='HSA', insurance_company_id='381f0ab3-1fb8-440f-81e6-6902dc60115a'),
            InsurancePlan(id='ab5d5419-245f-4b72-b2ce-4a4f87a95552', name='FloridaBlue 377', type='HMO', insurance_company_id='0a6f07e1-98c3-4dd8-b362-c718ce36f565'),

app/templates/appointment_confirmation.html
{% extends 'index.html' %}

{% block content %}

    <div class="flxc">
        <div class="right-side" style="width: 100%; text-align: center;">

            <h1>Congrats!</h1>
            <h4>Your appointment has been scheduled with {{ appointment.doctor.full_name }} on {{ appointment.date.strftime('%A %B %m, %Y') }}.</h4>
        </div>
    </div>

{% endblock content %}

app/templates/doctor_results.html
{% extends 'index.html' %}

{% block content %}

    <h1>Excellent! We were able to find {{ number }} doctor's that will accept your insurance.</h1>

    <hr/>


    {% for doctor in doctors %}

        <div class="right-side flxsb" style="width: 100%; margin: 20px 0 20px 0;">
            {{ doctor.full_name }}

            <a href="{{ url_for('base.schedule_appointment', doctor_id=doctor.id) }}">
                Schedule an appointment!
            </a>

        </div>
    {% endfor %}

{% endblock content %}

app/templates/find_doctor.html
{% extends 'index.html' %}

{% block content %}

    <h1>Find a Doctor</h1>
    <p><a href="{{ url_for('base.home') }}">< Back</a></p>
    <hr>

    <form action="" method="POST" style="margin-top: 40px;">

        {{ form.csrf_token }}
        {{ form.insurance_plan.label }}{{ form.insurance_plan }}

        <button type="submit" class="submit-btn" style="margin-top: 20px;">Submit</button>
    </form>

{% endblock content %}

app/templates/home.html
{% extends 'index.html' %}

{% block content %}

      <h1 style="font-size: 48px; text-align: center; padding-bottom: 40px; ">How can we help you today?</h1>

      <div class="flxc">
          <div class="right-side" style="text-align: center;">
              <h1>Find a Doctor</h1>
              <p>We will help you find a professional near you, that accepts your insurance!</p>
              <a href="{{ url_for('base.find_doctor') }}">
                  <button type="submit" class="submit-btn">Start Looking!</button>
              </a>
          </div>

          <div class="right-side" style="margin-left:40px; text-align: center;">
              <h1>New Appointment</h1>
              <p>If you already have a PCP we can help you schedule your next appointment.</p>
              <a href="{{ url_for('base.schedule_appointment', doctor_id='None') }}">
                <button type="submit" class="submit-btn">Get Started!</button>
              </a>
          </div>
      </div>

{% endblock content %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Olive | Healthcare Automation</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='base.css') }}">

    {% block head %}
    {% endblock head %}

</head>

<body>

<section id="topbar">

    <div class="boxed flxc">
        <div class="flxc" id="lftwrap">
            <a href="{{ url_for('base.home') }}">
                <div id="micon">

                    <?xml version="1.0" encoding="UTF-8"?>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 266.19 87.45">
                        <defs>
                            <style>.cls-1{fill:#651fff;}</style>
                        </defs>
                        <title>olive_vector</title>
                        <g id="Layer_2" data-name="Layer 2">
                            <g id="OLIVE_JDM" data-name="OLIVE JDM">
                                <path class="cls-1" d="M77.63,1c0,11.45-8,20.87-19.62,20.87-4.65,0-7.15-2.79-14.75-2.79a25.21,25.21,0,1,0,17.32,7,25.17,25.17,0,0,0,16.63-8.61A43.27,43.27,0,1,1,42.81,1Z"></path>
                                <rect class="cls-1" x="93.16" y="0.97" width="17.99" height="85.16"></rect>
                                <path class="cls-1" d="M129.54,0c-6.36,0-11.4,4.68-11.4,11s5,10.91,11.4,10.91,11.4-4.67,11.4-10.91a11.09,11.09,0,0,0-11.4-11"></path>
                                <rect class="cls-1" x="120.54" y="29.79" width="17.99" height="56.33"></rect>
                                <polygon class="cls-1" points="191.08 29.8 175.42 65.48 159.92 29.8 141.91 29.8 166.42 86.13 184.42 86.13 209.09 29.8 191.08 29.8"></polygon>
                                <path class="cls-1" d="M237,27.8c-40.75,0-40.74,59.65.84,59.65,13.89,0,24.62-7.19,27.57-18.38H247.24C243,75.8,227,75.14,224.19,62.74h41.62C268.62,41.25,255.55,27.8,237,27.8ZM224,52.51c1.54-7.21,6.42-10.89,13-10.89s11.22,3.61,12.21,10.89Z"></path>
                            </g>
                        </g>
                    </svg>

                </div>
            </a>
        </div>
    </div>

</section>

<div class="login-panel" style="position: absolute;">
    {% block content %}
    {% endblock %}
</div>


<footer style="position: absolute; bottom: 0; width: 100%; text-align: center; padding-bottom: 30px;">
    <p style="color: #651fff;">
        <i>*You can find the GitHub repo for this project
            <a href="https://github.com/jordanmslack/healthcare-automation"><b>here.</b></a>
        </i>
    </p>
</footer>

</body>

</html>

app/templates/schedule_appointment.html
{% extends 'index.html' %}

{% block content %}

    <h1>Schedule Appointment</h1>
    <p><a href="{{ url_for('base.home') }}">< Back</a></p>
    <hr>

    <form action="" method="POST" style="margin-top: 40px;">

        {{ form.csrf_token }}
        {{ form.doctor.label }}{{ form.doctor }}

        <div id="find-doc" style="display: none;">
            <p>Don't worry! We can help connect you with a doctor that accepts your insurance plan!</p>
            <a href="{{ url_for('base.find_doctor') }}">
                <button class="submit-btn" type="button">Find a Doctor!</button>
            </a>
        </div>

        <div id="schedule-hide">

            {{ form.date_time.label }}{{ form.date_time }}
            {{ form.first_name.label }}{{ form.first_name }}
            {{ form.last_name.label }}{{ form.last_name }}
            {{ form.email.label }}{{ form.email }}

            <button type="submit" class="submit-btn" style="margin-top: 20px;">Submit</button>
        </div>

    </form>

    <script>

        let scheduleHide = document.getElementById('schedule-hide')
            redirect = document.getElementById('find-doc')
            doctor = document.getElementById('doctor');

        doctor.addEventListener('change', async() => {

            let chosenType = doctor.options[doctor.selectedIndex].value;

            if (chosenType === 'no-doctor') {
                redirect.style.display = 'block';
                scheduleHide.style.display = 'none';
            } else {
                redirect.style.display = 'none';
                scheduleHide.style.display = 'block';
            }
        });

    </script>
{% endblock content %}